### PR TITLE
TASK-48123: Display pasted styled tables in notes

### PR DESCRIPTION
**Pull request by aelbenney**
The problem was in the WikiHTMLSanitizer when the notes body contains a comment and just below a closing tag. After splitting the body, the second part will contain closing tags without their opening ones. So in the HTMLSanitizer.sanitize() method, they will be removed.
This process was done with the old wiki app to conserve the xwiki content in comments. We no longer need it in the new notes app.

This fix should replace the `markupSanitize` with the `HTMLSanitizer` to remove useless html comments.

### CODE REVIEW

**Review by rdenarie — CHANGES_REQUESTED** [review]
Pr build fail

**Comment by rdenarie** [comment]
@ahamdi can you take a look on this PR.
Wdyt about using HTMLSanitizer instead of WikiHTMLSanitizer ?

**Comment by ahamdi** [comment]
@rdenarie WikiHTMLSanitizer was introduced tgo avoid losing Xwiki synta that was added in comments inside the source of the wiki pages. It is no more needed with the reworked Notes application

**Review by ahamdi — DISMISSED** [review]

**Review by rdenarie — CHANGES_REQUESTED** [review]
Can you rebase your pr to have only your commit ?

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
